# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
