# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160219_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='shared_with',
        ),
    ]
