# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_collection_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=2048)),
                ('audited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='blogged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('P', 'Private'), ('V', 'Visible on blog')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='blogcollection',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='webapp.Collection'),
        ),
    ]
